### ISSUE TITLE
application/notebook-controller

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#10]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
The notebook controller was more confusing than initially thought. 
The easiest way to check it up will be testing if it works. 

After trying to compare per file, and noticing that the file structure in manifest and 1.2-branch had been refactored for 1.3 and therefore many changes occured, it was suggested to do a `kustomize build` and compare the 'new' file and the 'old' one. The comparaison was done using [delta](https://github.com/dandavison/delta/releases).

There were quite a few little differences, included in RBAC. 

The one thing that might be an issue is that an RC version is used for image public.ecr.aws/j1r0q0g6/notebooks/notebook-controller:v1.3.0-rc.1 which we probably want to change. 
I found the images here: https://gallery.ecr.aws/j1r0q0g6/notebooks/notebook-controller
And chose to use the latest official release which is `v1.3.0`
*Note*: As of 2 weeks ago (August 18th 2021), a 1.4 release was done, but no tags indicate it's official status.

**Comment by wg102** [comment]
The big changes:

- 1.3 does not have ENABLE_CULLING and similar which came from a deployment.yaml patch.
- As mentionned above, a newer image is used for notebook-controller. Version 1.3.0 we will need to confirm it behaves as expected with our other components
-

**Comment by wg102** [comment]
There is an issue currently, I am not sure where it is coming from, be it the notebook-controller, jupyter-apis or maybe (but not likely) central-dashboard. 
Notebooks can be create. But when (on the UI), trying to delete a notebook is not working well.
The Pod gets to terminating, then deleted, but it then starts back on initialisation.
The notebook never actually gets deleted. 

It might have something to do with Statefulset.

**Comment by wg102** [comment]
After some additional testing, the notebook-controller started behaving normally. I am unable to track when it did, but deleting jupyter-web-app in it's integrality and waiting for it to restart seemed good.
The tag used for notebook-controller is 1.3rc1.0, the reason it's not 1.3 is that  from a comment, they are the same ( see https://github.com/kubeflow/kubeflow/commit/0e91a2b9cd0c3b6687692b1f1f09ac6070cc6c3e)

The reference of the image points to this : https://github.com/kubeflow/kubeflow/commit/8901e3af3b83f599b89562162cdb2854f57082d3 so 1.3rc1

**Comment by rohank07** [comment]
Tested:  Notebook is deleted and pod is terminated.
