### ISSUE TITLE
application/minio

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#11]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
After some discussion with @blairdrummond Minio will be postponed, there are some decision needed to be done on how to handle the hardcoded secrets, the backing up of data, service mesh etc. A lot of differences between us, 1.2 and upstream.

**Comment by rohank07** [comment]
Pipelines deployment files include minio manifests:
https://github.com/kubeflow/pipelines/blob/1.6.0/manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml
Manifests already deployed in pipelines: 
https://github.com/kubeflow/pipelines/tree/1.6.0/manifests/kustomize/third-party/minio/base

1 patch to be added: minio-pvc.yaml

**Comment by rohank07** [comment]
*Update no need to add patch persistent-volume-claim.yaml. 
Argoflow.py  initializes the size to 200 Gi already using an env variable `minio.size`

**Comment by rohank07** [comment]
Linking to the PR #32 as the issue that brings this one together.
and the issue #12
