### ISSUE TITLE
application/prob-notebook-controller

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#13]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
The following was done in [this commit](https://github.com/StatCan/argoflow-azure/commit/e453f97e08fd8c2d7a3acf254a791424d1055aa3):
1. Create prob-notebook-controller folder in distrubution/kubeflow/notebook 
2. Create file distribution/kubeflow/notebooks/prob-notebook-controller/kustomization.yaml

3. Copy the 4 following files in it. 
distribution/kubeflow/notebooks/prob-notebook-controller/cluster-role-binding.yaml
distribution/kubeflow/notebooks/prob-notebook-controller/cluster-role.yaml
distribution/kubeflow/notebooks/prob-notebook-controller/deployment.yaml
distribution/kubeflow/notebooks/prob-notebook-controller/service-account.yaml

4. Add this line `argocd-applications/prob-notebook-controller.yaml`
in the distribution/kustomization.yaml

5. Repeat the steps 1-4 for the template folder as well.

**Comment by wg102** [comment]
@blairdrummond  please review this

**Comment by blairdrummond** [comment]
LGTM!
