### ISSUE TITLE
application/admission-webhook

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#14]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Putting this here for posterity's sake.
After reviewing the difference between the 1.2 and 1.3 there are a couple differences, notably a possible merging of the kustomization file in v3 to the one under "base" <-- I think my mind saw the "commonLabels" and connected it to the 1.3 base.  However the 1.2 branch has the `v3`'s resources only had cert-manager and application.yaml under the resources. So to begin with I should have pointed to under overlays. 


I decided to just try it out using the 1.3 branch but run into this (the application state is never healthy, but the app stays synched which is good I guess)
![image](https://user-images.githubusercontent.com/23174198/131679606-d8255c88-6145-4af4-9344-d9d4a944dfe0.png)

Along with an error in the logs for the pod saying `F0831 1 config.go:44] config=main.Config{CertFile:"/etc/webhook/certs/cert.pem", KeyFile:"/etc/webhook/certs/key.pem"} Error: open /etc/webhook/certs/cert.pem: no such file or directory`

I may try looking / pointing to the kustomize file in the overlays/cert-manager (just this has it going out of sync but not healthy) to see what happens (or maybe i point to both in the resources?)

Also use https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#base (i thought for whatever reason they just had names for names)

**Comment by Jose-Matsuda** [comment]
Also in our https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/kustomize/application/admission-webhook/application.yaml we have `addownerref: False`

**Comment by Jose-Matsuda** [comment]
If I try to point to both resources, I get App Health of "Healthy" but an error of 
![image](https://user-images.githubusercontent.com/23174198/131886738-4525212f-dc22-4bdf-a3e5-17e98c07f543.png)

I have cert-manager first and then base in the kustomization under the resources.

**Comment by Jose-Matsuda** [comment]
Pointing to just `overlays` has a reasonable "out of sync" issue of the mutating webhook changing what's on the deployment, vs whats on the git repo. (It says synced but it's really not) 
![image](https://user-images.githubusercontent.com/23174198/132373425-a6b5ca4a-7168-488f-8d25-1d88f78e66aa.png)

Have argocd configured to ignore this. 

Having said that a _**LOT**_ of resources seem to be running into the same issue (of the manifest changing). Tried adding some ignore for the MutatingWebhook but don't think it's working

Admission-webhook was really just renamed to poddefaults

**Comment by Jose-Matsuda** [comment]
I went digging in the issues of [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/issues?q=poddefaults+application) as well as the kubeflow/manifest repos and only really found [this](https://github.com/kubeflow/kubeflow/pull/5719/files) where application.yaml was deleted. 
In the issue/conversation they also mention the following,
![image](https://user-images.githubusercontent.com/23174198/134104552-7387025e-476f-4582-acd0-e73ec028d829.png)

I will do a final review of poddefaults with someone else before closing this

**Comment by Jose-Matsuda** [comment]
Doing a test WITH pod-defaults still kicking (in argocd)
![image](https://user-images.githubusercontent.com/23174198/134183814-3121ba35-90fb-49ec-8453-4b07b062197e.png)


WITHOUT
![image](https://user-images.githubusercontent.com/23174198/134183756-86c4fba0-bdc1-44f4-9192-ba9933693bbf.png)

**Comment by Jose-Matsuda** [comment]
Closing after confirming that poddefaults was indeed admission-webhook, as well as going through the changes mentioned by upstream [here](https://github.com/kubeflow/kubeflow/pull/5719/files), also contains in the discussion area the removal of `application`
