### ISSUE TITLE
application/metadata

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#17]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by rohank07** [comment]
Metadata is already deployed in pipelines. There are no patches on aaw-kubeflow-manifest.
https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/kustomize/application/metadata/kustomization.yaml
![image](https://user-images.githubusercontent.com/28408586/136448658-eb055603-f64e-4f4a-82d6-94304c285072.png)

**Comment by rohank07** [comment]
Linking to the PR #32 as the issue that brings this one together.
and the issue #12
