### ISSUE TITLE
application/mysql

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#18]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
https://github.com/kubeflow/manifests/tree/v1.2-branch/pipeline/mysql --> under installs/generic for what we use currently.
https://github.com/kubeflow/manifests/tree/v1.3-branch/apps/pipeline/upstream/third-party/mysql --> 1.3 in manifests
which is basically https://github.com/kubeflow/pipelines/tree/master/manifests/kustomize/third-party in kubeflow/pipelines

**Comment by Jose-Matsuda** [comment]
1.2 installs/generic references [platform-agnostic](https://github.com/kubeflow/manifests/blob/v1.2-branch/pipeline/upstream/env/platform-agnostic/mysql/kustomization.yaml) which is mostly the same as what is in 1.3 [here](https://github.com/kubeflow/manifests/blob/v1.3-branch/apps/pipeline/upstream/third-party/mysql/base/kustomization.yaml) except 1.3 now has a ServiceAccount.

Some more information too look at is 
https://github.com/kubeflow/pipelines/issues/5133
and 
https://github.com/kubeflow/pipelines/pull/5256/files

Under resources there is also the `../../overlays/application/application.yaml`

**Comment by Jose-Matsuda** [comment]
Upon inspection in the pipelines deployment manifest we already do have mysql brought in as seen in 
https://github.com/kubeflow/pipelines/blob/1.6.0/manifests/kustomize/env/platform-agnostic-multi-user/kustomization.yaml#L9 and there are no patches on our end.

We just need to review pipelines and ensure it works.

**Comment by Jose-Matsuda** [comment]
Linking to the PR https://github.com/StatCan/aaw-argoflow-azure/pull/32 as the issue that brings this one together.
and the issue https://github.com/StatCan/aaw-argoflow-azure/issues/12
