### ISSUE TITLE
Argoflow manifest verify namespaces

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#20]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

________
Adding details to this issue.
There is a folder named namespaces under https://github.com/StatCan/aaw-kubeflow-manifest/tree/master/kustomize/namespaces
We need to verify if this is still valid, and if we should use this patch, no patch, or a new version of a patch.

Another thing that might be wise to test are the default namespaces created.

**Comment by Jose-Matsuda** [comment]
Ours
https://github.com/StatCan/aaw-kubeflow-manifest/tree/master/kustomize/namespaces

1.2
https://github.com/kubeflow/manifests/tree/v1.2-branch/namespaces/base

1.3
https://github.com/kubeflow/manifests/blob/v1.3-branch/common/kubeflow-namespace/base/namespace.yaml

**Comment by Jose-Matsuda** [comment]
Both namespace and cert manager seem to be deployed and healthy. Will just apply the patch and check if it works

**Comment by Jose-Matsuda** [comment]
In the patch it removes the control-plane label and I have added the label `katib-metricscollector-injection` to this list of labels to remove as I do not know what it is for.
 
After running and deploying it seems to be good

**Comment by Jose-Matsuda** [comment]
Closing (as completed)
