### ISSUE TITLE
Argoflow manifest - metacontroller

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#22]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by rohank07** [comment]
No patches for metacontroller in 
https://github.com/StatCan/aaw-kubeflow-manifest/blob/399a615fc49d4b30f7124924eefcb0389fc1ad22/kustomize/metacontroller/kustomization.yaml
It can reference upstream tag 1.6.0

**Comment by rohank07** [comment]
Linking to the PR #32 as the issue that brings this one together.
and the issue #12
