### ISSUE TITLE
Argoflow Manifest - application/katib

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#23]

**Comment by wg102** [comment]
We may need to bring this in even if it is not i18n yet. The agreement was to not remove it.

**Comment by rohank07** [comment]
old (aaw-kubeflow-mainfests)
https://github.com/StatCan/aaw-kubeflow-manifest/tree/master/kustomize/application/katib
1.2
https://github.com/kubeflow/manifests/tree/v1.2-branch/katib/installs/katib-standalone
1.3
https://github.com/kubeflow/katib/tree/release-0.11/manifests/v1beta1/installs/katib-with-kubeflow

**Comment by rohank07** [comment]
Upgrading Katib to [Katib v0.12.0](https://github.com/kubeflow/katib/releases/tag/v0.12.0) 

Issues using v0.11.0 in [katib-mysql](https://github.com/kubeflow/katib/blob/v0.11.0/manifests/v1beta1/components/mysql/mysql.yaml)
![image](https://user-images.githubusercontent.com/28408586/139453110-b41f5ea5-ecd4-4fd9-a6b7-418376bf84e1.png)
![image](https://user-images.githubusercontent.com/28408586/139453290-12eeac84-6172-4346-bd86-33c08deb7587.png)
Link to the discussion  https://github.com/kubeflow/katib/issues/1479
Left side v0.11.0  vs Right side v0.12.0
![image](https://user-images.githubusercontent.com/28408586/139449460-924523fb-5d44-4be2-aa12-884308fe780b.png)
Includes failureThreshold in the `livenessprob` and `startupProbe`.  Also made `initialDelaySeconds` less than 30 seconds.

Upgrade to Katib v0.12.0 uses  tag mysql:8.0.26, upgrading from 8.0.22.
