### ISSUE TITLE
Argoflow Manifest knative

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#25]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Blair seems to have put this in already so we just need to verify that it works / check it over

**Comment by rohank07** [comment]
Knative already deployed to argo. 

aaw-kubeflow-manifest (ours)
https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/kustomize/knative/kustomization.yaml

v1.2 
https://github.com/kubeflow/manifests/blob/v1.2.0/knative/installs/generic/kustomization.yaml

v1.3
https://github.com/kubeflow/manifests/tree/v1.3-branch/common/knative/knative-serving/base/upstream

Eventing also deployed (optional) by David Spec 

Convo with Blair- Knative is deployed and operational in our clusters.
