### ISSUE TITLE
Argoflow Manifest application/pytorch-job

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#26]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Ours
https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/kustomize/application/pytorch-job/kustomization.yaml

1.2
https://github.com/kubeflow/manifests/tree/v1.2-branch/pytorch-job

1.3

https://github.com/kubeflow/manifests/tree/v1.3.0/apps/pytorch-job

And good reading might be 
https://github.com/kubeflow/pytorch-operator#installing-pytorch-operator where it does say that this installs both (perhaps just combined)

**Comment by rohank07** [comment]
Pytorch-operator was already deployed. Kubeflow/manifest branch  v1.3 was missing pytorch-job-crds (existed on v1.2). It does not exist anymore in v1.3 kubeflow/manifest and v0.7 in kubeflow/pytorch-operator.

**Comment by rohank07** [comment]
ReadMe includes how to deploy pytorch job https://github.com/kubeflow/pytorch-operator#installing-pytorch-operator

**Comment by rohank07** [comment]
May leave this for now. Minimize work to deploy as not necessarily being used at the moment. Will leave everything in but in commented form.
