### ISSUE TITLE
Argoflow Manifest application/tf-training

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#27]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Ours
https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/kustomize/application/tf-training/kustomization.yaml

1.2
https://github.com/kubeflow/manifests/tree/v1.2-branch/tf-training

1.3
https://github.com/kubeflow/manifests/tree/v1.3.0/apps/tf-training

Seems to be in a similar position to pytorch as in the install also looks at the standalone
https://github.com/kubeflow/training-operator#installation

**Comment by rohank07** [comment]
tf-training already deployed, verified deploying in to argo-CD. Application synced and healthy.

**Comment by Jose-Matsuda** [comment]
for some reason didnt close

**Comment by rohank07** [comment]
May leave this for now. Minimize work to deploy as not necessarily being used at the moment. Will leave everything in but in commented form.
