### ISSUE TITLE
Argoflow Manifest application/mxnet-job

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#28]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
Ours 
https://github.com/StatCan/aaw-kubeflow-manifest/tree/master/kustomize/application/mxnet-job

1.2
https://github.com/kubeflow/manifests/tree/v1.2-branch/mxnet-job/mxnet-operator/overlays/application

1.3 
https://github.com/kubeflow/manifests/tree/v1.3.0/apps/mxnet-job

Seems a bit different but we will see

**Comment by Jose-Matsuda** [comment]
May leave this for now. Minimize work to deploy as not necessarily being used at the moment. Will  leave everything in but in commented form.
