### ISSUE TITLE
Add Cron.yaml

### ISSUE THREAD

**Issue by rohank07** [StatCan/argoflow-azure#34]
Add cron job to distribution/kubeflow/pipelines from https://github.com/StatCan/aaw-kubeflow-manifest/blob/master/.github/workflows/cron.yml

**Comment by Jose-Matsuda** [comment]
Came up because the number of nodes maxed out on prod. Previously we had a cronjob to clean up old argo workflow runs (the one linked by Rohan above)

**Comment by rohank07** [comment]
Version 1.18 of kubernetes uses apiversion: batch/v1beta1. A newer stable version 1.21 uses apiversion: batch/v1. Once we update to 1.21 we should also update the apiversion.

UPDATE: Changed to v1beta

**Comment by rohank07** [comment]
closes https://github.com/StatCan/aaw-argocd-manifests/pull/9

**Comment by rohank07** [comment]
To run a cron job dealing with argo cli workflow; I had to install argoflow workflows on the kind cluster. `kubectl create ns argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml`

Cronjob uses argoproj/argocli:latest to execute argo workflow commands.

Need a ClusterRole and ClusterRolebinding to delete at cluster level instead of at namspace level. 

PR https://github.com/StatCan/aaw-argocd-manifests/pull/9
