### ISSUE TITLE
ArgoCD - Downgrade Istio

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#35]
We want to be as aligned as possible with the istio version. 
Istio 1.5 is what is used for kubeflow 1.2.
There is some discusssion about how to process to upgrade versions : https://github.com/kubeflow/kubeflow/issues/5176#issuecomment-725363913

We need to decide which version to use. According to documentation, anything above 1.4 (So it includes authorization Policies) would be ok.

**Comment by rohank07** [comment]
Downgraded istio-operator to 1.7.0 but Istio-resources fails to sync kubeflow-userid & kubeflow-gateway... "the server could not find the requested resource"

**Comment by wg102** [comment]
Just updating the number in the istio-operator file is not enought, as mentionned in a previous comment. We started to look more into the structure of the Gateway kind of file, and the EnvoyFilter, for 1.7 specifically
- https://istio.io/v1.7/docs/reference/config/networking/envoy-filter/
- https://istio.io/v1.7/docs/reference/config/networking/gateway/
a few things are different such as apiVersion, filtername, subFilterName etc. 
So far changing those as well has had no positive impact

**Comment by rohank07** [comment]
![image](https://user-images.githubusercontent.com/28408586/138487302-3a3e6dfa-5846-4e22-beb9-176a4a2d57bb.png)

Istio v1.7.0 does not support kubernetes v1.22.1
Also, to note Istio v1.10.0 does not support kubernetes (tested, but not supported) v1.22.1

https://istio.io/latest/docs/releases/supported-releases/#support-status-of-istio-releases


kind cluster
![image](https://user-images.githubusercontent.com/28408586/138500299-b1cda9de-e6ca-48ef-9db7-2df3346fc63d.png)

**Comment by rohank07** [comment]
Production cluster aaw-prod-cc-00-aks kubernetes client version 1.21 server version 1.19

**Comment by rohank07** [comment]
![image](https://user-images.githubusercontent.com/28408586/139092083-ff9ce004-6c8b-49c0-9632-b0c79816a374.png)

istio-operator pod log output
