### ISSUE TITLE
application/seldon

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#5]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
Work done in https://github.com/StatCan/argoflow-azure/commit/cf0bc051dcba7e30a39c9cc5ad89307b3a91e598

**Comment by wg102** [comment]
Seldon was successfully done in the commit mentionned above. 
One thing to note is that the application, on Argo-CD is Healthy but out of Sync. 
Further investigation revealed that it was out of sync because of the Certicate (in base64 encoding), it was visible in the Manifest difference in Argo-CD.

Since certificates change quite often, this is not an issue currently, just something to keep an eye on.

**Comment by wg102** [comment]
@blairdrummond can you review this please?

**Comment by rohank07** [comment]
Tested Seldon CRD [Christian's example](https://github.com/chritter/argo_seldon_deployments/tree/master/getting-started) argo_app.yaml. 

Successful output from ` kubectl port-forward services/iris-model-default 9000:8000 -n seldon-system`

![Screenshot from 2021-09-15 18-42-56](https://user-images.githubusercontent.com/28408586/133519545-fa45e2bd-cf57-44c6-a03a-eb9f83c1e096.png)
Scaled to 2 pods.
