### ISSUE TITLE
application/spark-operator

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#6]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by Jose-Matsuda** [comment]
1.2
https://github.com/kubeflow/manifests/blob/v1.2-branch/stacks/azure/application/spark-operator/kustomization.yaml which leads to 
https://github.com/kubeflow/manifests/tree/v1.2-branch/spark/spark-operator

1.3 
https://github.com/kubeflow/manifests/tree/v1.3-branch/contrib/spark/spark-operator

Looking at the two they are exactly the same

**Comment by rohank07** [comment]
May leave this for now. Minimize work to deploy as not necessarily being used at the moment. Will leave everything in but in commented form. Commenting out Spark-operator (backlog). Decided not to bring in everything from second-priority (deploy minimal product). 

Spark operator not syncing; [upstream](https://github.com/kubeflow/manifests/blob/v1.3-branch/contrib/spark/spark-operator/overlays/application/application.yaml) api-version references v1beta1. Kind uses api v1alpha1. Possibility the spec's format his changed.
