### ISSUE TITLE
application/centraldashboard

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#7]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
The disctibution folder currently point to [kubeflow's](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard/manifests/overlays/istio) manifest directly.

I am not sure where the enable-refistration-flow.yaml patch comes from. does not seem to be centraldashboard.
It's in our manifest1.2/common/centraldashboard/base/deployment_patch.yaml

So are things about KFRAM_service_host

**Comment by wg102** [comment]
Ready for review @blairdrummond 

Initial commit : https://github.com/StatCan/argoflow-azure/commit/74ea526d6ed753585fac3e820973dfacd33c2d18
Aditional commmit : https://github.com/StatCan/argoflow-azure/commit/787ccefcebbc964be8cb24f0d24446bc778ab030
With seting the registration_flow value to true in this commit: https://github.com/StatCan/argoflow-azure/commit/e453f97e08fd8c2d7a3acf254a791424d1055aa3
Copy to template folder: https://github.com/StatCan/argoflow-azure/commit/76ed71b2473bab3f2c3621a835de2aa90e49db11

- enable-registration-flow.yaml - comes from the deployment_patch.yaml in branch 1.2 and the values in the .env file.

- Do we need an image in the kustomization.yaml file? There are none in the distribution folder, but in upstream:

```
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newName: public.ecr.aws/j1r0q0g6/notebooks/central-dashboard
  newTag: v1.3.0-rc.1
```
and similar code pointing to a different url are found on the 1.2 branch.

**Comment by blairdrummond** [comment]
LGTM!
