### ISSUE TITLE
application/jupyter-web-app

### ISSUE THREAD

**Issue by wg102** [StatCan/argoflow-azure#8]
Compare our manifest and kubeflow's, with careful checking for any customization.
Update the argoflow-azure applications in distribution
Test
Duplicate the changes in the template.

**Comment by wg102** [comment]
Ready for review @blairdrummond 
Initial commit: https://github.com/StatCan/aaw-argoflow-azure/commit/74ea526d6ed753585fac3e820973dfacd33c2d18
https://github.com/StatCan/aaw-argoflow-azure/commit/787ccefcebbc964be8cb24f0d24446bc778ab030
modification for prob-controller:  https://github.com/StatCan/aaw-argoflow-azure/commit/e453f97e08fd8c2d7a3acf254a791424d1055aa3

I compared the result between our current manifest for jupyter-web-apps and the distribution folder using 
`kustomize build --load-restrictor LoadRestrictionsNone . | yat`

There are a few differences such as missing labels, additional configmaps and such. 
Also the current distribution has the logos that are related to crud-web-app. 
But this should not be an issue.

Side note the kustomization file is points to

**Comment by rohank07** [comment]
Tested: Created and deleted notebook server successfully.
